# Fictional Army - Filtering and Sorting

### Introduction:

This exercise was inspired by this [page](http://chrisalbon.com/python/)

Special thanks to: https://github.com/chrisalbon for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [66]:
import pandas as pd

### Step 2. This is the data given as a dictionary

In [67]:
# Create an example dataframe about a fictional army
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']}

### Step 3. Create a dataframe and assign it to a variable called army. 

#### Don't forget to include the columns names in the order presented in the dictionary ('regiment', 'company', 'deaths'...) so that the column index order is consistent with the solutions. If omitted, pandas will order the columns alphabetically.

In [91]:
army = pd.DataFrame.from_dict(raw_data)
print(army.head())

     regiment company  deaths  battles  size  veterans  readiness  armored  \
0  Nighthawks     1st     523        5  1045         1          1        1
1  Nighthawks     1st      52       42   957         5          2        0
2  Nighthawks     2nd      25        2  1099        62          3        1
3  Nighthawks     2nd     616        2  1400        26          3        1
4    Dragoons     1st      43        4  1592        73          2        0

   deserters      origin
0          4     Arizona
1         24  California
2         31       Texas
3          2     Florida
4          3       Maine

### Step 4. Set the 'origin' colum as the index of the dataframe

In [94]:
army.set_index("origin", inplace=True)

### Step 5. Print only the column veterans

In [95]:
veterans = army.loc[:,["veterans"]]
veterans.head(10)

            veterans
origin
Arizona            1
California         5
Texas             62
Florida           26
Maine             73
Iowa              37
Alaska           949
Washington        48
Oregon            48
Wyoming          435

### Step 6. Print the columns 'veterans' and 'deaths'

In [96]:
vet_death = army.loc[:,["veterans","deaths"]]
vet_death.head()

            veterans  deaths
origin
Arizona            1     523
California         5      52
Texas             62      25
Florida           26     616
Maine             73      43

### Step 7. Print the name of all the columns.

In [97]:
army.columns

Index(['regiment', 'company', 'deaths', 'battles', 'size', 'veterans',
       'readiness', 'armored', 'deserters'],
      dtype='object')

### Step 8. Select the 'deaths', 'size' and 'deserters' columns from Maine and Alaska

In [104]:
maine_alaska = army.loc[['Maine', 'Alaska'],["deaths","size","deserters"]]
maine_alaska.head()

        deaths  size  deserters
origin
Maine       43  1592          3
Alaska     523   987         24

### Step 9. Select the rows 3 to 7 and the columns 3 to 6

In [105]:
slicer = army.iloc[3:8,3:7]
slicer.head()

            battles  size  veterans  readiness
origin
Florida           2  1400        26          3
Maine             4  1592        73          2
Iowa              7  1006        37          1
Alaska            8   987       949          2
Washington        3   849        48          3

### Step 10. Select every row after the fourth row and all columns

In [106]:
slicer2 = army.iloc[4:,:]
slicer2.head()

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2

### Step 11. Select every row up to the 4th row and all columns

In [107]:
slicer3 = army.iloc[:5,:]
slicer3.head()

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3

### Step 12. Select the 3rd column up to the 7th column

In [108]:
slicer4 = army.iloc[:,3:8]
slicer4.head()

            battles  size  veterans  readiness  armored
origin
Arizona           5  1045         1          1        1
California       42   957         5          2        0
Texas             2  1099        62          3        1
Florida           2  1400        26          3        1
Maine             4  1592        73          2        0

### Step 13. Select rows where df.deaths is greater than 50

In [109]:
slicer5= army.loc[army["deaths"]>50]
slicer5.head()

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24

### Step 14. Select rows where df.deaths is greater than 500 or less than 50

In [110]:
slicer6= army.loc[(army['deaths'] > 500) | (army['deaths'] < 50)]
slicer6.head()

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Alaska,Dragoons,2nd,523,8,987,949,2,0,24

### Step 15. Select all the regiments not named "Dragoons"

In [111]:
slicer7= army.loc[(army['regiment'] != "Dragoons")]
slicer7.head()

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Oregon,Scouts,1st,62,4,973,48,2,0,2

### Step 16. Select the rows called Texas and Arizona

In [112]:
slicer8 = army.loc[["Texas", "Arizona"], :]
slicer8.head()

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4

### Step 17. Select the third cell in the row named Arizona

In [116]:
slicer9 = army.loc[["Arizona"]].iloc[:, 2]
slicer9.head()

origin
Arizona    523
Name: deaths, dtype: int64

### Step 18. Select the third cell down in the column named deaths

In [130]:
slicer10 = army.loc[:, ["deaths"]].iloc[2]
slicer10.head()

deaths    25
Name: Texas, dtype: int64